version: "3.8"
   
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_HOST: "db"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    environment:
      - POSTGRES_DB=vynils
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - default
